name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop    

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: step build
        run: echo "Hello World" > helloWorld.txt
      - name: upload file to artifact
        uses: actions/upload-artifact@v2
        with:
          name: helloWorld
          path: ./helloWorld.txt
          retention-days: 5

  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: list files before download
        run: ls -lrth --color
      - name: download file from artifact
        uses: actions/download-artifact@v2
        with:
          name: helloWorld
      - name: list files after download
        run: ls -lrth --color
      - name: step test
        run: grep "Hello World" helloWorld.txt
