name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop    

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: step build
        run: echo "Hello World" > helloWorld.txt
      - name: upload file to artifact
        uses: actions/upload-artifact@v2
        with:
          name: helloWorld
          path: ./helloWorld.txt
          retention-days: 5

  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: list files before download
        run: ls -lrth --color
      - name: download file from artifact
        uses: actions/download-artifact@v2
        with:
          name: helloWorld
      - name: list files after download
        run: ls -lrth --color
      - name: step test
        run: grep "Hello World" helloWorld.txt

  quality:
    name: quality
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      start_step: ${{ steps.inicio.outputs.start_step }}
      end_step: ${{ steps.fim.outputs.end_step }}
    steps:
      - name: Inicio
        id: inicio
        run: |
          echo "::set-output name=start_step::$(date +%s%3N)"
          

      - name: download file from artifact
        uses: actions/download-artifact@v2
        with:
          name: helloWorld

      - name: Fim
        id: fim
        run: |
          echo "::set-output name=end_step::$(date +%s%3N)"
          
      - name: Consolidado
        run: |          
          echo "Start Step: ${{ needs.quality.outputs.start_step }}"
          echo "End Step: ${{ needs.quality.outputs.end_step }}"